name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Create project structure
      run: |
        mkdir -p app/src/main/java/com/example/app
        mkdir -p app/src/main/res/layout
        mkdir -p gradle/wrapper
        
    - name: Create build files
      run: |
        # Create build.gradle (root)
        cat > build.gradle << 'EOF'
        buildscript {
            repositories { google(); mavenCentral() }
            dependencies { classpath 'com.android.tools.build:gradle:8.1.4' }
        }
        allprojects {
            repositories { google(); mavenCentral() }
        }
        task clean(type: Delete) { delete rootProject.buildDir }
        EOF
        
        # Create app/build.gradle
        cat > app/build.gradle << 'EOF'
        plugins { id 'com.android.application' }
        android {
            compileSdk 34
            namespace 'com.example.app'
            defaultConfig {
                applicationId "com.example.app"
                minSdk 21
                targetSdk 34
                versionCode 1
                versionName "1.0"
            }
            buildTypes { debug { debuggable true } }
        }
        dependencies { implementation 'androidx.appcompat:appcompat:1.6.1' }
        EOF
        
        # Create AndroidManifest.xml
        cat > app/src/main/AndroidManifest.xml << 'EOF'
        <?xml version="1.0" encoding="utf-8"?>
        <manifest xmlns:android="http://schemas.android.com/apk/res/android"
            package="com.example.app">
            <application android:label="My App">
                <activity android:name=".MainActivity" android:exported="true">
                    <intent-filter>
                        <action android:name="android.intent.action.MAIN" />
                        <category android:name="android.intent.category.LAUNCHER" />
                    </intent-filter>
                </activity>
            </application>
        </manifest>
        EOF
        
        # Create MainActivity.java
        cat > app/src/main/java/com/example/app/MainActivity.java << 'EOF'
        package com.example.app;
        import android.os.Bundle;
        import android.widget.TextView;
        import androidx.appcompat.app.AppCompatActivity;
        public class MainActivity extends AppCompatActivity {
            @Override
            protected void onCreate(Bundle savedInstanceState) {
                super.onCreate(savedInstanceState);
                TextView textView = new TextView(this);
                textView.setText("Привет! Успех!");
                textView.setTextSize(32);
                setContentView(textView);
            }
        }
        EOF
        
        # Create settings.gradle
        echo "include ':app'" > settings.gradle
        
        # Create gradle wrapper properties
        cat > gradle/wrapper/gradle-wrapper.properties << 'EOF'
        distributionBase=GRADLE_USER_HOME
        distributionPath=wrapper/dists
        distributionUrl=https\://services.gradle.org/distributions/gradle-8.6-bin.zip
        zipStoreBase=GRADLE_USER_HOME
        zipStorePath=wrapper/dists
        EOF

    - name: Download and setup Gradle
      run: |
        wget -q https://github.com/gradle/gradle/releases/download/v8.6/gradle-8.6-bin.zip
        unzip -q gradle-8.6-bin.zip
        echo "GRADLE_HOME=$PWD/gradle-8.6" >> $GITHUB_ENV
        echo "$PWD/gradle-8.6/bin" >> $GITHUB_PATH
        
    - name: Build APK
      run: |
        gradle assembleDebug --no-daemon
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: my-app
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 1
